/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com._3ksystema.relatorios;

import com._3ksystema.classes.FormataData;
import com._3ksystema.classes.FormataNumeros;
import com._3ksystema.modelos.Cliente;
import com._3ksystema.modelos.Empresa;
import com._3ksystema.modelos.Venda;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DecimalFormat;

/**
 * @author Mariano Junior
 */
public class GerarContrato {
    
    private FormataData fd = new FormataData();
    private DecimalFormat df = new DecimalFormat("#,###.00");
    
    public void gerarContrato(Cliente cliente, Empresa empresa, Venda venda) throws FileNotFoundException, DocumentException, IOException {
        Document documento = new Document();
        documento.setPageSize(PageSize.A4);
        documento.setMargins(30, 30, 20, 20);
        String nomeDocumento = "Contrato de Compra.pdf";
        PdfWriter.getInstance(documento, new FileOutputStream(nomeDocumento));
        documento.open();
        String texto = "CONTRATO DE VENDA DE MÓVEIS E ELETRO ELETRÔNICOS";
        Paragraph paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(1);
        documento.add(paragrafo);
        texto = " ";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(0);
        documento.add(paragrafo);
        texto = "IDENTIFICAÇÃO DAS PARTES";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(0);
        documento.add(paragrafo);
        texto = " ";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(0);
        documento.add(paragrafo);
        texto = "Pelo presente instrumento particular de compromisso de compra e venda, de um lado " + empresa.getNomeEmpresa() +", CNPJ n.º " + empresa.getCnpjEmpresa() + ", situada na rua " + empresa.getRuaEmpresa() + ", n.º " + empresa.getNumEmpresa() + ", cidade de " + empresa.getCidadeEmpresa() + ", Estado " + empresa.getEstadoEmpresa() + ", representado neste ato pelo sócio gerente " + empresa.getDirEmpresa() + ", portador da carteira de identidade RG. " + empresa.getRgDirEmpresa() + ", de ora adiante chamado de VENDEDOR, e do outro lado ( pessoa física) " + cliente.getNome_Cliente() + ", portadora do carteira de identidade RG n.º " + cliente.getRg_Cliente() + " - " + cliente.getOrg_Emissor_RG_Cliente() + " - " + cliente.getEstado_Emissor_RG_Cliente() + ", inscrita no CPF n.º " + cliente.getCpf_Cliente() + ", residente e domiciliado na rua " + cliente.getRua_Casa_Cliente() + ", n.º " + cliente.getNumero_Casa_Cliente() + ", Cidade " + cliente.getCidade_Casa_Cliente() + ", Estado " + cliente.getEstado_Casa_Cliente() + ", de ora em diante chamada de COMPRADOR, tem, entre si, como justo e contatado o que se segue:";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(3);
        documento.add(paragrafo);
        texto = " ";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(0);
        documento.add(paragrafo);
        texto = "CLÁUSULA PRIMEIRA - DO OBJETO";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(3);
        documento.add(paragrafo);
        texto = "O VENDEDOR vende ao COMPRADOR, pelo preço certo e ajustado de R$ " + df.format(venda.getValorVenda()) + ".";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(3);
        documento.add(paragrafo);
        texto = "As partes acima identificadas têm, entre si, justo e acertado o presente Contrato de Venda de Produtos, que se regerá pelas cláusulas seguintes e pelas condições descritas no presente.";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(3);
        documento.add(paragrafo);
        texto = " ";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(0);
        documento.add(paragrafo);
        texto = "CLÁUSULA SEGUNDA - GARANTIA";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(3);
        documento.add(paragrafo);
        texto = "O VENDEDOR disponibilizara garantia de ______________ para a mercadoria firmada contrato por este instrumento de venda.";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(3);
        documento.add(paragrafo);
        texto = " ";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(3);
        documento.add(paragrafo);
        texto = "CLÁUSULA TERCEIRA - PAGAMENTO";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(0);
        documento.add(paragrafo);
        texto = "O pagamento do objeto contratual poderá ser à vista ou de forma parcelada.";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(3);
        documento.add(paragrafo);
        texto = " ";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(0);
        documento.add(paragrafo);
        texto = "Parágrafo Primeiro: O pagamento do objeto à vista é realizado em dinheiro, cheque, Cartão de Débito e ou Crédito. Caso, o cheque não apresente saldo, o contrato não estará adimplido.";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(3);
        documento.add(paragrafo);
        texto = " ";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(0);
        documento.add(paragrafo);
        texto = "Parágrafo Segundo: O pagamento de forma parcelada, será realizado de acordo com a emissão de boleto das prestações do carnê proprio da loja sob análise de Crédito.";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(3);
        documento.add(paragrafo);
        texto = " ";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(0);
        documento.add(paragrafo);
        texto = "CLÁUSULA QUARTA - IMPONTUALIDADE DO PAGAMENTO";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(3);
        documento.add(paragrafo);
        texto = "O pagamento não realizado pelo COMPRADOR na data pactuada entre os contratantes, incidirá em:";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(3);
        documento.add(paragrafo);
        texto = "a) multa penal de 2% ( dois ) sobre o valor";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(3);
        documento.add(paragrafo);
        texto = "b) correção monetária de acordo com os índices IPC, IGP, etc.";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(0);
        documento.add(paragrafo);
        texto = "c) Juros de 1% (um) ao mês.";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(3);
        documento.add(paragrafo);
        texto = " ";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(0);
        documento.add(paragrafo);
        texto = "CLÁUSULA SEXTA - INADIMPLEMENTO CONTRATUAL";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(3);
        documento.add(paragrafo);
        texto = "Ocorrendo a inadimplência do pagamento da obrigação assumida pelo COMPRADOR, além do ônus previsto no cláusula Quarta deste contrato, o COMPRADOR, será responsável por todas despesas que o VENDEDOR tiver de dispor para realizar a cobrança extrajudicial e judicial, realizado diretamente pelo seu departamento de cobrança ou por terceiros que prestem este serviço.";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(3);
        documento.add(paragrafo);
        texto = " ";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(3);
        documento.add(paragrafo);
        texto = "CLÁUSULA SÉTIMA - FORO";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(0);
        documento.add(paragrafo);
        texto = "As partes elegem o foro desta cidade para dirimir as questões oriundas deste contrato, com renúncia de qualquer outro, por mais privilegiado que seja.";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(3);
        documento.add(paragrafo);
        texto = " ";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(0);
        documento.add(paragrafo);
        texto = "E por estarem as partes, COMPRADOR e VENDEDOR, em pleno acordo, em tudo quanto se encontra disposto neste instrumento particular, assinam-no em duas vias destinando-se uma via para cada contratante.";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(3);
        documento.add(paragrafo);
        texto = " ";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(0);
        documento.add(paragrafo);
        texto = empresa.getCidadeEmpresa()  + " - " + empresa.getEstadoEmpresa() + ", " + fd.dataExtenso() + ".";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(1);
        documento.add(paragrafo);
        texto = " ";
        paragrafo = new Paragraph(texto);
        paragrafo.setAlignment(0);
        documento.add(paragrafo);
        PdfPTable tabela = new PdfPTable(2);
        tabela.setWidthPercentage(100);
        tabela.setPaddingTop(0);
        texto = "____________________________\n" + cliente.getNome_Cliente() + "\nCPF: " + cliente.getCpf_Cliente();
        paragrafo = new Paragraph(texto);
        PdfPCell cel1 = new PdfPCell(paragrafo);
        texto = "____________________________\n" + empresa.getNomeEmpresa() + "\nCNPJ: " + empresa.getCnpjEmpresa();
        paragrafo = new Paragraph(texto);
        PdfPCell cel2 = new PdfPCell(paragrafo);
        cel1.setBorder(Rectangle.NO_BORDER);
        cel2.setBorder(Rectangle.NO_BORDER);
        cel1.setPadding(0);
        cel2.setPadding(0);
        cel1.setHorizontalAlignment(1);
        cel2.setHorizontalAlignment(1);
        tabela.addCell(cel1);
        tabela.addCell(cel2);
        documento.add(tabela);
        documento.close();
        Desktop.getDesktop().open(new File(nomeDocumento));
    }
}
