/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com._3ksystema.telas;

import com._3ksystema.funcoes.FuncaoCarne;
import com._3ksystema.funcoes.FuncoesCliente;
import com._3ksystema.funcoes.FuncoesVenda;
import com._3ksystema.modelos.Carne;
import com._3ksystema.modelos.Cliente;
import com._3ksystema.modelos.Venda;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mariano Junior
 */
public class HistoricoComprasCliente extends javax.swing.JInternalFrame {

    Cliente cliente = new Cliente();
    FuncoesCliente fc = new FuncoesCliente();
    Venda venda = new Venda();
    FuncoesVenda fv = new FuncoesVenda();
    Carne carne = new Carne();
    FuncaoCarne fcn = new FuncaoCarne();
    
    /**
     * Creates new form HistoricoComprasCliente
     * @throws java.lang.ClassNotFoundException
     */
    public HistoricoComprasCliente() throws ClassNotFoundException {
        initComponents();
        listaClientes();
        jPanelVendas.setVisible(false);
        jPanelParcelas.setEnabled(false);
        jPanelVendas.setEnabled(false);
    }

    private void listaClientes() throws ClassNotFoundException{
        tblClientes.setModel(DbUtils.resultSetToTableModel(fc.listaNomesClientes()));
    }
    
    private Cliente pegaCliente() throws ClassNotFoundException{
        return fc.pesquisaCliente(tblClientes.getModel().getValueAt(tblClientes.getSelectedRow(), 0).toString());
    }
    
    private int selecionaCliente(Cliente cliente) throws ClassNotFoundException{
        int idCliente = cliente.getId_Cliente();
        tblHistoricoCompras.setModel(DbUtils.resultSetToTableModel(fv.buscaVendaCliente(idCliente)));
        return idCliente;
    }
    
    private String pegaVenda() throws ClassNotFoundException{
        return tblHistoricoCompras.getModel().getValueAt(tblHistoricoCompras.getSelectedRow(), 0).toString();
    }
    
    private void listCarnes(int idCliente, int idVenda){
        tblHistoricoPagamentos.setModel(DbUtils.resultSetToTableModel(fcn.historicoCarnesCliente(idCliente, idVenda)));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelCliente = new javax.swing.JPanel();
        txtPesquisaCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        jPanelVendas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHistoricoCompras = new javax.swing.JTable();
        jPanelParcelas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHistoricoPagamentos = new javax.swing.JTable();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Historico de Clientes");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtPesquisaCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        javax.swing.GroupLayout jPanelClienteLayout = new javax.swing.GroupLayout(jPanelCliente);
        jPanelCliente.setLayout(jPanelClienteLayout);
        jPanelClienteLayout.setHorizontalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPesquisaCliente)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelClienteLayout.setVerticalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pesquisa", jPanelCliente);

        jPanelVendas.setEnabled(false);

        tblHistoricoCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Data", "Forma de Pagamento", "Valor"
            }
        ));
        tblHistoricoCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHistoricoComprasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblHistoricoCompras);

        javax.swing.GroupLayout jPanelVendasLayout = new javax.swing.GroupLayout(jPanelVendas);
        jPanelVendas.setLayout(jPanelVendasLayout);
        jPanelVendasLayout.setHorizontalGroup(
            jPanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelVendasLayout.setVerticalGroup(
            jPanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Histórico de Compras", jPanelVendas);

        jPanelParcelas.setEnabled(false);

        tblHistoricoPagamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Valor da Parcela", "Data de Vencimento", "Data de Pagamento"
            }
        ));
        jScrollPane3.setViewportView(tblHistoricoPagamentos);

        javax.swing.GroupLayout jPanelParcelasLayout = new javax.swing.GroupLayout(jPanelParcelas);
        jPanelParcelas.setLayout(jPanelParcelasLayout);
        jPanelParcelasLayout.setHorizontalGroup(
            jPanelParcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParcelasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelParcelasLayout.setVerticalGroup(
            jPanelParcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParcelasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Histórico de Pagamentos", jPanelParcelas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        try {
            // TODO add your handling code here:
            cliente = pegaCliente();
            selecionaCliente(cliente);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HistoricoComprasCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblClientesMouseClicked

    private void tblHistoricoComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHistoricoComprasMouseClicked
        try {
            // TODO add your handling code here:
            String datavenda = pegaVenda();
            venda = fv.pesquisaClienteData(datavenda, cliente.getId_Cliente());
            listCarnes(venda.getCliente(), venda.getIdVenda());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HistoricoComprasCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblHistoricoComprasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelCliente;
    private javax.swing.JPanel jPanelParcelas;
    private javax.swing.JPanel jPanelVendas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTable tblHistoricoCompras;
    private javax.swing.JTable tblHistoricoPagamentos;
    private javax.swing.JTextField txtPesquisaCliente;
    // End of variables declaration//GEN-END:variables
}
