/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com._3ksystema.telas;

import com._3ksystema.classes.FormataData;
import com._3ksystema.funcoes.FuncaoCarne;
import com._3ksystema.funcoes.FuncoesEmpresa;
import com._3ksystema.modelos.Empresa;
import java.sql.SQLException;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mariano Junior
 */
public class ListaClienteAtrasados extends javax.swing.JInternalFrame {
    
    private FuncaoCarne fcn = new FuncaoCarne();
    private FormataData fd = new FormataData();
    private Empresa empresa = new Empresa();
    private FuncoesEmpresa fe = new FuncoesEmpresa();

    /**
     * Creates new form ListaClienteAtrasados
     * @throws java.lang.ClassNotFoundException
     */
    public ListaClienteAtrasados() throws ClassNotFoundException, SQLException {
        initComponents();
        listarClientesAtrasadors();
        empresa = fe.pesquisaEmpresa();
        lblNomeTela.setText("Listagem de clientes com parcelas atrasadas - " + empresa.getNomeEmpresa());
    }

    private void listarClientesAtrasadors() throws ClassNotFoundException{
        tblDevedores.setModel(DbUtils.resultSetToTableModel(fcn.listaCarnesAtrasados(fd.dataSQL())));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeTela = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDevedores = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Relatório de clientes com parcelas atrasadas");

        lblNomeTela.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNomeTela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeTela.setText("Listagem de clientes com parcelas atrasadas - Crediario São Jorge");

        tblDevedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome do Cliente", "Telefone", "Data Vencimento", "Valor"
            }
        ));
        jScrollPane1.setViewportView(tblDevedores);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Pesquisa:");

        txtPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Pesquisar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeTela, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtPesquisar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomeTela)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNomeTela;
    private javax.swing.JTable tblDevedores;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
