/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com._3ksystema.telas;

import com._3ksystema.classes.FormataData;
import com._3ksystema.classes.FormataNumeros;
import com._3ksystema.funcoes.FuncoesSaida;
import com._3ksystema.modelos.Saidas;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mariano Junior
 */
public class TelaSaidaCaixa extends javax.swing.JInternalFrame {

    Saidas saida = new Saidas();
    FuncoesSaida fs = new FuncoesSaida();
    FormataData fd = new FormataData();
    FormataNumeros fn = new FormataNumeros();
    int idSaida = 0;

    /**
     * Creates new form TelaSaidaCaixa
     */
    public TelaSaidaCaixa() {
        initComponents();
        txtData.setText(fd.dataAtualBr());
        btnExclui.setEnabled(false);
    }

    private void sairTelaSaida() {
        int sair = JOptionPane.showConfirmDialog(null, "Deseja Sair da tela de Saida de caixa?", "Aviso", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }

    private void salvaSaida() throws ClassNotFoundException {
        saida.setNaturezaSaida(txtMotivo.getText());
        saida.setDataSaida(fd.formataData(txtData.getText()));
        saida.setValorSaida(Double.parseDouble(fn.ConverterFloat(txtValor.getText())));
        fs.salvaSaida(saida);
        limpaCampos();
    }

    private void editaSaida() throws ClassNotFoundException {
        fs.alteraSaida(saida);
    }

    private void excluiSaida() throws ClassNotFoundException {
        saida = fs.pesquisaSaida(txtMotivo.getText());
        fs.excluirSaida(idSaida);
        btnExclui.setEnabled(false);
        btnSalva.setEnabled(true);
        limpaCampos();
    }

    private Saidas pesquisaSaida() throws ClassNotFoundException {
        return fs.pesquisaSaida(txtMotivo.getText());
    }

    private void setaCampos() throws ClassNotFoundException {
        saida = pesquisaSaida();
        idSaida = saida.getIdSaida();
        txtMotivo.setText(saida.getNaturezaSaida());
        txtData.setText(fd.dataBr(saida.getDataSaida()));
        txtValor.setText(fn.FloatConvertido(Double.toString(saida.getValorSaida())));
    }

    private void limpaCampos() {
        txtMotivo.setText("");
        txtData.setText("");
        txtValor.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMotivo = new javax.swing.JTextField();
        txtData = new javax.swing.JFormattedTextField();
        btnSair = new javax.swing.JButton();
        btnExclui = new javax.swing.JButton();
        btnPesquisa = new javax.swing.JButton();
        btnSalva = new javax.swing.JButton();
        txtValor = new javax.swing.JFormattedTextField();

        setTitle("Movimentação de saídas financeiras");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Saídas");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Motivo:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Data:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Valor:");

        txtMotivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnSair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSair.setText("Sair");
        btnSair.setPreferredSize(new java.awt.Dimension(110, 30));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnExclui.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExclui.setText("Excluir");
        btnExclui.setPreferredSize(new java.awt.Dimension(110, 30));
        btnExclui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluiActionPerformed(evt);
            }
        });

        btnPesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisa.setText("Pesquisar");
        btnPesquisa.setPreferredSize(new java.awt.Dimension(110, 30));
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        btnSalva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalva.setText("Salvar");
        btnSalva.setPreferredSize(new java.awt.Dimension(110, 30));
        btnSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvaActionPerformed(evt);
            }
        });

        txtValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMotivo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExclui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExclui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        sairTelaSaida();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        // TODO add your handling code here:
        if (txtMotivo.getText().isEmpty()) {
            try {
                ResultSet rs = fs.resgataSaidas(txtData.getText());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaSaidaCaixa.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (txtData.getText().isEmpty()) {
            try {
                saida = fs.pesquisaSaida(txtMotivo.getText());
                setaCampos();
                btnExclui.setEnabled(true);
                btnSalva.setText("Atualizar");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaSaidaCaixa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void btnExcluiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluiActionPerformed
        try {
            // TODO add your handling code here:
            excluiSaida();
            limpaCampos();
            btnExclui.setEnabled(false);
            btnSalva.setText("Salvar");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaSaidaCaixa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnExcluiActionPerformed

    private void btnSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaActionPerformed
        // TODO add your handling code here:
        if (btnSalva.getText().equals("Salvar")) {
            try {
                salvaSaida();
                limpaCampos();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaSaidaCaixa.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                editaSaida();
                limpaCampos();
                btnExclui.setEnabled(false);
                btnSalva.setText("Salvar");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaSaidaCaixa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSalvaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExclui;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtMotivo;
    private javax.swing.JFormattedTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
