/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com._3ksystema.telas;

import com._3ksystema.classes.EntradasTableModel;
import com._3ksystema.classes.FormataData;
import com._3ksystema.classes.FormataNumeros;
import com._3ksystema.classes.SaidasTableModel;
import com._3ksystema.funcoes.FuncoesCaixa;
import com._3ksystema.funcoes.FuncoesEntrada;
import com._3ksystema.funcoes.FuncoesSaida;
import com._3ksystema.modelos.Caixa;
import com._3ksystema.modelos.Entradas;
import com._3ksystema.modelos.Saidas;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mariano Junior
 */
public class TelaAbreEFechaCaixa extends javax.swing.JInternalFrame {

    private Caixa cx = new Caixa();
    private Saidas saida = new Saidas();
    private FuncoesCaixa fc = new FuncoesCaixa();
    private FuncoesSaida fs = new FuncoesSaida();
    private FuncoesEntrada fe = new FuncoesEntrada();
    private FormataData fd = new FormataData();
    private FormataNumeros fn = new FormataNumeros();
    private TelaPrincipal tp;
    private DecimalFormat df = new DecimalFormat("#,###.00");
    private ArrayList<Saidas> saidas = new ArrayList();
    private ArrayList<Entradas> entradas = new ArrayList();
    private EntradasTableModel etm = new EntradasTableModel();
    private SaidasTableModel stm = new SaidasTableModel();
    
    /**
     * Creates new form TelaAbreEFechaCaixa
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    public TelaAbreEFechaCaixa() throws ClassNotFoundException, SQLException {
        initComponents();
        txtDataCaixa.setText(fd.dataAtualBr());
        tblListaCaixas.setModel(DbUtils.resultSetToTableModel(fc.listaCaixas()));
        
    }

    private void sairOpcCaixa(){
        int sair = JOptionPane.showConfirmDialog(null, "Deseja encerrar a abertura de caixa?", "Aviso", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (sair == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }
    
    private void abrirCaixa() throws ClassNotFoundException{
        cx.setDataCaixa(fd.dataSQL());
        cx.setNomeCaixa(fd.dataAtualBr());
        cx.setValorAbertura(Double.parseDouble(fn.ConverterFloat(txtValorAbertura.getText())));
        cx.setValorFechamento(0.0);
        //System.out.println("Nome do caixa: " + cx.getNomeCaixa() + "\nData do Caixa: " + cx.getDataCaixa() + "\nValor Abertura: " + cx.getValorAbertura() + "\nValor Fechamento: " + cx.getValorFechamento());
        fc.abrirCaixa(cx);
        tp.btnVenda.setEnabled(true);
        tp.jMenuItem2.setEnabled(true);
        tp.jMenuItem3.setEnabled(true);
    }
    
    private void fecharCaixa() throws ClassNotFoundException{
        saidas = fs.saidasDia(fd.dataSQL());
        double valorSaida = fs.calculaTotalSaidas(saidas);
        entradas = fe.entradasDoDia(fd.dataSQL());
        double valorEntrada = fe.somaValorEntradaData(entradas);
        cx = fc.pesquisaCaixa(fd.dataAtualBr());
        double valorEmCaixa = (cx.getValorAbertura() + valorEntrada) - valorSaida;
        int confirmaFechamento = JOptionPane.showConfirmDialog(null, "O Caixa do dia " + fd.dataAtualBr() + 
                "\nAberto com o valor: R$ " + df.format(cx.getValorAbertura()) + "\nCom o arrecadado diário de: R$ " + df.format(valorEntrada) +
                "\nCom o pagamento diário de: R$ " + df.format(valorSaida) + "\nE um total liquido de: R$ " +
                df.format(valorEmCaixa), "Confirmação de dados", JOptionPane.YES_NO_OPTION);
        if (confirmaFechamento == JOptionPane.YES_OPTION) {
            txtDataCaixa.setText(cx.getNomeCaixa());
            txtValorAbertura.setText(fn.FloatConvertido(String.valueOf(cx.getValorAbertura())));
            cx = fc.pegaUltimoCaixa();
            cx.setValorFechamento(valorEmCaixa);
            fc.atualizaCaixa(cx);
        }
    }
    
    private void pesquisaData(){
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jpaCaixa = new javax.swing.JTabbedPane();
        panCaixa = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaCaixas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDataCaixa = new javax.swing.JTextField();
        txtValorAbertura = new javax.swing.JTextField();
        txtValorFechamento = new javax.swing.JTextField();
        txtNomeDataPesquisa = new javax.swing.JFormattedTextField();
        btnSair = new javax.swing.JButton();
        btnFecharCaixa = new javax.swing.JButton();
        btnAbrirCaixa = new javax.swing.JButton();
        btnPesquisaCaixa = new javax.swing.JButton();
        panEntradas = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEntradasDetalhadas = new javax.swing.JTable();
        panSaidas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSaidasDetalhadas = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setTitle("Abrir e Fechar Caixa");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Caixa");

        tblListaCaixas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblListaCaixas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListaCaixasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListaCaixas);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Data:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Valor Abertura:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Valor Fechado:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Pesquisa:");

        txtDataCaixa.setEditable(false);
        txtDataCaixa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtValorAbertura.setEditable(false);
        txtValorAbertura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtValorFechamento.setEditable(false);
        txtValorFechamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        try {
            txtNomeDataPesquisa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNomeDataPesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValorAbertura))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDataCaixa)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtValorFechamento)
                    .addComponent(txtNomeDataPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(txtDataCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeDataPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtValorAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtValorFechamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSair.setText("Sair");
        btnSair.setPreferredSize(new java.awt.Dimension(110, 30));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnFecharCaixa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFecharCaixa.setText("Fechar");
        btnFecharCaixa.setPreferredSize(new java.awt.Dimension(110, 30));
        btnFecharCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharCaixaActionPerformed(evt);
            }
        });

        btnAbrirCaixa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAbrirCaixa.setText("Abrir");
        btnAbrirCaixa.setPreferredSize(new java.awt.Dimension(110, 30));
        btnAbrirCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirCaixaActionPerformed(evt);
            }
        });

        btnPesquisaCaixa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisaCaixa.setText("Pesquisar");
        btnPesquisaCaixa.setPreferredSize(new java.awt.Dimension(110, 30));

        javax.swing.GroupLayout panCaixaLayout = new javax.swing.GroupLayout(panCaixa);
        panCaixa.setLayout(panCaixaLayout);
        panCaixaLayout.setHorizontalGroup(
            panCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panCaixaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPesquisaCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAbrirCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFecharCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );
        panCaixaLayout.setVerticalGroup(
            panCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFecharCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAbrirCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisaCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpaCaixa.addTab("Caixas", panCaixa);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Entradas Detalhadas");

        tblEntradasDetalhadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblEntradasDetalhadas);

        javax.swing.GroupLayout panEntradasLayout = new javax.swing.GroupLayout(panEntradas);
        panEntradas.setLayout(panEntradasLayout);
        panEntradasLayout.setHorizontalGroup(
            panEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEntradasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE))
                .addContainerGap())
        );
        panEntradasLayout.setVerticalGroup(
            panEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEntradasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpaCaixa.addTab("Entradas", panEntradas);

        tblSaidasDetalhadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblSaidasDetalhadas);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Saidas Detalhadas");

        javax.swing.GroupLayout panSaidasLayout = new javax.swing.GroupLayout(panSaidas);
        panSaidas.setLayout(panSaidasLayout);
        panSaidasLayout.setHorizontalGroup(
            panSaidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSaidasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panSaidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE))
                .addContainerGap())
        );
        panSaidasLayout.setVerticalGroup(
            panSaidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panSaidasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        jpaCaixa.addTab("Saidas", panSaidas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpaCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpaCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        sairOpcCaixa();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAbrirCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirCaixaActionPerformed
        // Abrir Caixa
        String valorAbertura = JOptionPane.showInputDialog(null, "Qual o valor em caixa na abertura?");
        txtValorAbertura.setText(valorAbertura);
        try {
            abrirCaixa();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaAbreEFechaCaixa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAbrirCaixaActionPerformed

    private void btnFecharCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharCaixaActionPerformed
        try {
            // TODO add your handling code here:
            fecharCaixa();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaAbreEFechaCaixa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFecharCaixaActionPerformed

    private void tblListaCaixasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaCaixasMouseClicked
        // TODO add your handling code here:
        String data = tblListaCaixas.getModel().getValueAt(tblListaCaixas.getSelectedRow(), 0).toString();
        data = fd.formataData(data);
        try {
            saidas = fs.saidasDia(data);
            entradas = fe.entradasDoDia(data);
            stm.setLinhas(saidas);
            etm.setLinhas(entradas);
            tblEntradasDetalhadas.setModel(etm);
            tblSaidasDetalhadas.setModel(stm);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaAbreEFechaCaixa.class.getName()).log(Level.SEVERE, null, ex);
        }
        //System.out.println(data);
    }//GEN-LAST:event_tblListaCaixasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirCaixa;
    private javax.swing.JButton btnFecharCaixa;
    private javax.swing.JButton btnPesquisaCaixa;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jpaCaixa;
    private javax.swing.JPanel panCaixa;
    private javax.swing.JPanel panEntradas;
    private javax.swing.JPanel panSaidas;
    private javax.swing.JTable tblEntradasDetalhadas;
    private javax.swing.JTable tblListaCaixas;
    private javax.swing.JTable tblSaidasDetalhadas;
    private javax.swing.JTextField txtDataCaixa;
    private javax.swing.JFormattedTextField txtNomeDataPesquisa;
    private javax.swing.JTextField txtValorAbertura;
    private javax.swing.JTextField txtValorFechamento;
    // End of variables declaration//GEN-END:variables
}
